Repository chc5/gitgud, pull requests merged in 2018-12, with the labels that each got.

#31 Chc complaint system
  client/src/actions/actions_doc_complaint.js
  client/src/actions/actions_notification.js
  client/src/actions/actions_user_complaint.js
  client/src/components/Complaint/Complaint.css
  client/src/components/Complaint/Complaint.js
  client/src/components/Notice/Notice.js
  client/src/containers/DocComplaint/DocComplaint.css
  client/src/containers/DocComplaint/DocComplaint.js
  client/src/containers/Document/Document.css
  client/src/containers/Document/Document.js
  client/src/containers/DocumentManager/DocumentManager.css
  client/src/containers/DocumentManager/DocumentManager.js
  client/src/containers/Home/Home.css
  client/src/containers/Home/Home.js
  client/src/containers/Login/Login.css
  client/src/containers/Login/Login.js
  client/src/containers/Signup/Signup.css
  client/src/containers/Signup/Signup.js
  client/src/containers/UserComplaint/UserComplaint.css
  client/src/containers/UserComplaint/UserComplaint.js
  client/src/reducers/reducers_complaint.js
  client/src/reducers/reducers_doc_list.js
  client/src/reducers/reducers_notification.js
Labels: enhancement

#32 Taboo suggestion, approval, and removal. Taboo check on updating doc
  server/controllers/docHandlers.js
  server/controllers/taboo.js
  server/database/models/doc.js
  server/database/models/taboo.js
  server/routes/index.js
  server/routes/taboo.js
Labels: enhancement

#37 Added DocComplaint popups
  client/src/actions/actions_doc_complaint.js
  client/src/components/Complaint/Complaint.js
  client/src/components/DocComplaint/DocComplaint.css
  client/src/components/DocComplaint/DocComplaint.js
  client/src/components/UserComplaint/UserComplaint.css
  client/src/components/UserComplaint/UserComplaint.js
  client/src/constants/types_doc_complaint_action.js
  client/src/constants/types_user_complaint_action.js
  client/src/containers/DocComplaintForm/DocComplaintForm.js
  client/src/containers/DocComplaintManager/DocComplaintManager.js
  client/src/containers/UserComplaintForm/UserComplaintForm.js
  client/src/containers/UserComplaintManager/UserComplaintManager.js
  client/src/reducers/index.js
  client/src/reducers/reducers_complaint.js
Labels: enhancement

#35 Fixed revision saving to collection before checking taboo
  server/controllers/docHandlers.js
Labels: bug

#40 Added creation of document as first revision
  server/controllers/docHandlers.js
  server/database/models/doc.js
Labels: enhancement

#38 Added TabooWordManager and updated its UI
  client/src/actions/actions_doc_complaint.js
  client/src/actions/actions_taboo.js
  client/src/actions/actions_user_complaint.js
  client/src/constants/types_error.js
  client/src/constants/types_taboo_action.js
  client/src/containers/DocComplaintManager/DocComplaintManager.js
  client/src/containers/DocumentManager/DocumentManager.js
  client/src/containers/TabooWordManager/TabooWordManager.css
  client/src/containers/TabooWordManager/TabooWordManager.js
  client/src/containers/UserComplaintManager/UserComplaintManager.js
  client/src/reducers/index.js
  client/src/reducers/reducers_approved_taboo.js
  client/src/reducers/reducers_unapproved_taboo.js
Labels: enhancement

#39 Populated complaints with names
  server/controllers/complaintHandler.js
  server/routes/taboo.js
Labels: bug, enhancement

#41 added a /
  server/routes/taboo.js
Labels: bug

#42 populated revisions array
  server/controllers/docHandlers.js
Labels: enhancement

#47 refactored logged in check for requests
  server/controllers/authentication.js
  server/controllers/complaintHandler.js
  server/controllers/docHandlers.js
  server/controllers/taboo.js
  server/routes/complaints/docComplaint.js
  server/routes/complaints/userComplaint.js
  server/routes/docs.js
  server/routes/taboo.js
Labels: enhancement

#46 user profiles CRUD
  server/controllers/profileHandler.js
  server/database/models/userProfile.js
  server/routes/account.js
Labels: enhancement

#49 Role permissions and checking
  server/authentication/index.js
  server/controllers/authentication.js
  server/controllers/complaintHandler.js
  server/controllers/docHandlers.js
  server/controllers/profileHandler.js
  server/controllers/promotion.js
  server/controllers/roleCheck.js
  server/controllers/taboo.js
  server/controllers/testing.js
  server/database/models/promotion.js
  server/database/models/roleConfig.js
  server/database/models/roles.js
  server/database/models/user.js
  server/routes/index.js
  server/routes/promotion.js
Labels: enhancement

#52 Chc lock unlock
  client/src/actions/actions_doc_complaint.js
  client/src/actions/actions_document.js
  client/src/actions/actions_lock.js
  client/src/actions/actions_notification.js
  client/src/components/DocComplaint/DocComplaint.js
  client/src/components/DocumentList/DocumentList.js
  client/src/constants/types_doc_complaint_action.js
  client/src/constants/types_document_action.js
  client/src/containers/DocComplaintManager/DocComplaintManager.js
  client/src/containers/Document/Document.js
  client/src/containers/DocumentManager/DocumentManager.js
  client/src/containers/Home/Home.js
  client/src/containers/TabooWordManager/TabooWordManager.js
  client/src/reducers/reducers_approved_taboo.js
  client/src/reducers/reducers_doc_list.js
Labels: enhancement

#54 added method to retrieve all user profiles
  server/controllers/profileHandler.js
  server/routes/account.js
Labels: enhancement

#56 Chc user profiles
  client/src/App.js
  client/src/actions/actions_doc_complaint.js
  client/src/actions/actions_document.js
  client/src/actions/actions_lock.js
  client/src/actions/actions_notification.js
  client/src/actions/actions_profile.js
  client/src/actions/actions_user_complaint.js
  client/src/components/DocComplaint/DocComplaint.js
  client/src/components/Invitation/Invitation.css
  client/src/components/Invitation/Invitation.js
  client/src/components/UserComplaint/UserComplaint.js
  client/src/constants/types_document_action.js
  client/src/constants/types_error.js
  client/src/constants/types_profile_action.js
  client/src/constants/types_user_complaint_action.js
  client/src/constants/types_user_profile.js
  client/src/containers/DocComplaintManager/DocComplaintManager.css
  client/src/containers/Document/Document.css
  client/src/containers/Document/Document.js
  client/src/containers/ProfileManager/ProfileManager.css
  client/src/containers/ProfileManager/ProfileManager.js
  client/src/containers/Setting/Setting.css
  client/src/containers/Setting/Setting.js
  client/src/containers/Signup/Signup.js
  client/src/containers/UserComplaintManager/UserComplaintManager.js
  client/src/reducers/index.js
  client/src/reducers/reducers_doc_complaint.js
  client/src/reducers/reducers_profile.js
  client/src/reducers/reducers_profile_list.js
  client/src/reducers/reducers_user_complaint.js
Labels: enhancement

#57 Document privacy
  server/controllers/docHandlers.js
  server/database/models/doc.js
  server/routes/docs.js
Labels: enhancement

#58 fixed result typo to findResult
  server/controllers/docHandlers.js
Labels: bug

#59 Added a Privacy Settings pop-up
  client/src/App.js
  client/src/actions/actions_document.js
  client/src/components/DocumentList/DocumentList.js
  client/src/components/PrivacySettings/PrivacySettings.css
  client/src/components/PrivacySettings/PrivacySettings.js
  client/src/constants/types_document_action.js
  client/src/constants/types_permission.js
  client/src/containers/DocumentManager/DocumentManager.js
Labels: enhancement

#61 default profile creation for users
  server/controllers/authentication.js
Labels: enhancement

#62 changed invite to add by username
  server/controllers/docHandlers.js
  server/controllers/profileHandler.js
Labels: enhancement

#64 Chc promotion
  client/src/App.js
  client/src/actions/actions_profile.js
  client/src/actions/actions_promotion.js
  client/src/components/Invitation/Invitation.js
  client/src/components/Profile/Profile.css
  client/src/components/Profile/Profile.js
  client/src/components/UserComplaint/UserComplaint.js
  client/src/constants/types_error.js
  client/src/constants/types_permission.js
  client/src/constants/types_promotion.js
  client/src/containers/Document/Document.js
  client/src/containers/DocumentManager/DocumentManager.js
  client/src/containers/Home/Home.js
  client/src/containers/NavBar/NavBar.js
  client/src/containers/ProfileManager/ProfileManager.css
  client/src/containers/ProfileManager/ProfileManager.js
  client/src/containers/PromotionManager/PromotionManager.css
  client/src/containers/PromotionManager/PromotionManager.js
  client/src/containers/Setting/Setting.js
  client/src/containers/TabooWordManager/TabooWordManager.js
  client/src/containers/UserComplaintManager/UserComplaintManager.js
  client/src/reducers/index.js
  client/src/reducers/reducers_profile.js
  client/src/reducers/reducers_promotion_list.js
Labels: enhancement

#68 Chc refactoring
  client/src/actions/actions_account_registration.js
  client/src/actions/actions_doc_complaint.js
  client/src/actions/actions_document.js
  client/src/actions/actions_lock.js
  client/src/actions/actions_profile.js
  client/src/actions/actions_promotion.js
  client/src/actions/actions_taboo.js
  client/src/actions/actions_user_complaint.js
  client/src/actions/actions_user_escalation.js
  client/src/components/DocComplaint/DocComplaint.js
  client/src/components/DocumentList/DocumentList.js
  client/src/components/Profile/Profile.js
  client/src/components/UserComplaint/UserComplaint.js
  client/src/constants/types_container.js
  client/src/constants/types_doc_complaint_action.js
  client/src/constants/types_permission.js
  client/src/constants/types_profile_action.js
  client/src/constants/types_promotion.js
  client/src/constants/types_taboo_action.js
  client/src/constants/types_user_action.js
  client/src/constants/types_user_complaint_action.js
  client/src/constants/types_user_profile.js
  client/src/containers/Document/Document.js
  client/src/containers/Home/Home.js
  client/src/containers/NavBar/NavBar.js
  client/src/containers/ProfileManager/ProfileManager.js
  client/src/containers/PromotionManager/PromotionManager.js
  client/src/containers/Setting/Setting.js
  client/src/containers/Signup/Signup.js
  client/src/containers/TabooWordManager/TabooWordManager.js
  client/src/containers/UserComplaintManager/UserComplaintManager.js
Labels: enhancement
